name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22] # active LTS + current
    steps:
      - uses: actions/checkout@v4 # get your code
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm # built-in dependency cache
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm test -- --coverage
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.node }}
          path: |
            coverage/**
            junit.xml
          if-no-files-found: ignore
